version: '3.9'

services:
  web:
    build: .
    container_name: malaria_prediction
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data  # Volume pour sauvegarder les données de prédiction
    environment:
      FLASK_APP: run.py  # Spécifie le point d'entrée Flask
      DATA_PATH: /data   # Chemin du dossier de sauvegarde des données
    command: flask run --host=0.0.0.0 --port=5000

volumes:
  data:
    driver: local